nrf-bl: add sha256sums & checks for 3rd party tools

diff --git a/utils/nrf-bootloader/Makefile b/utils/nrf-bootloader/Makefile
--- a/utils/nrf-bootloader/Makefile
+++ b/utils/nrf-bootloader/Makefile
@@ -2,9 +2,9 @@
 IMAGE_NAME := nrf-toolchain 
 DOCKER_USER := $(shell id -u):$(shell id -g)
 
-.PHONY: all enter clean
+.PHONY: all enter clean verify
 
-all: $(IMAGE_NAME).built
+all: $(IMAGE_NAME).built verify
 	docker run -it \
 		--user $(DOCKER_USER) \
 		-v $(shell pwd):/work \
@@ -18,7 +18,19 @@ enter:
 		$(IMAGE_NAME) \
 		bash
 
-
+verify:
+	if [[ "4" == "$(shell docker run -it \
+		--user $(DOCKER_USER) \
+		-v $(shell pwd):/work \
+		$(IMAGE_NAME) \
+		sha256sum -c /work/sha256sums.txt | grep -c "OK")" ]]; \
+	then \
+		echo "Verification OK"; \
+	else \
+		echo "Verification FAILED"; \
+		exit 1; \
+	fi 
+	
 $(IMAGE_NAME).built: Dockerfile
 	docker build -t $(IMAGE_NAME) .
 	touch $<
